import os, json, sqlite3
from datetime import datetime
from pathlib import Path
from fastapi import FastAPI, Request, Form, UploadFile, File
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from starlette.middleware.sessions import SessionMiddleware
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="PocketSmart AI")
app.add_middleware(SessionMiddleware, secret_key=os.getenv("SESSION_SECRET", "change-this-secret"))
app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

DB = "pocketsmart.db"
UPLOAD_DIR = Path("static/uploads")
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

def db():
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    return con

def init_db():
    con = db()
    con.execute("""CREATE TABLE IF NOT EXISTS users(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password TEXT NOT NULL)""")
    con.execute("""CREATE TABLE IF NOT EXISTS history(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER, planner TEXT, budget REAL, input_data TEXT,
        result TEXT, created_at TEXT)""")
    con.commit()
    con.close()

init_db()

def save_history(user_id, planner, budget, input_data, result):
    con = db()
    con.execute("INSERT INTO history(user_id,planner,budget,input_data,result,created_at) VALUES(?,?,?,?,?,?)",
                (user_id, planner, budget, json.dumps(input_data), json.dumps(result), datetime.now().isoformat(timespec="seconds")))
    con.commit(); con.close()

def get_user(request):
    uid = request.session.get("user_id")
    if not uid: return None
    con = db(); row = con.execute("SELECT * FROM users WHERE id=?", (uid,)).fetchone(); con.close()
    return row

def fallback_home(budget, room, style):
    items = [
        ("LED Ceiling Light", "Amazon", min(900, budget*0.15), "Lighting"),
        ("Modern Wall Art", "IKEA", min(1200, budget*0.20), "Decor"),
        ("Compact Storage Unit", "IKEA", min(2500, budget*0.30), "Furniture"),
        ("Decorative Plant", "Amazon", min(700, budget*0.10), "Decor"),
    ]
    return {"planner":"Home Interior","summary":f"Budget ₹{budget:,.0f} for a {style} {room}.",
            "recommendations":[{"item":a,"platform":b,"price":round(c,0),"category":d} for a,b,c,d in items],
            "note":"Demo recommendations are generated locally. Add GEMINI_API_KEY for AI-generated suggestions."}

def fallback_party(budget, guests, event):
    food=budget*.45; decor=budget*.25; entertainment=budget*.20; misc=budget*.10
    return {"planner":"Party Planner","summary":f"{event.title()} for {guests} guests within ₹{budget:,.0f}.",
            "allocation":{"Food & Catering":round(food),"Decoration":round(decor),"Entertainment":round(entertainment),"Miscellaneous":round(misc)},
            "recommendations":[
                {"item":"Catering package","platform":"Swiggy / Zomato","price":round(food),"category":"Food"},
                {"item":"Decoration package","platform":"Local / online vendors","price":round(decor),"category":"Decoration"},
                {"item":"Venue / stay option","platform":"OYO / Local venues","price":round(entertainment),"category":"Venue"}
            ],
            "note":"Demo budget allocation. Add GEMINI_API_KEY for AI-generated planning."}

def fallback_jewelry(budget, occasion, style):
    return {"planner":"Jewelry Planner","summary":f"{style.title()} jewelry for {occasion} within ₹{budget:,.0f}.",
            "recommendations":[
                {"item":"Minimal gold-tone earrings","platform":"Amazon","price":round(min(900,budget*.25)),"category":"Earrings"},
                {"item":"Matching necklace set","platform":"Flipkart","price":round(min(1800,budget*.45)),"category":"Necklace"},
                {"item":"Bangle set","platform":"Amazon","price":round(min(1000,budget*.20)),"category":"Bangles"}
            ],
            "note":"Upload an outfit image for a future multimodal Gemini integration."}

async def gemini_generate(prompt, image_bytes=None, mime_type=None):
    key = os.getenv("GEMINI_API_KEY")
    if not key:
        return None
    try:
        from google import genai
        client = genai.Client(api_key=key)
        parts = [prompt]
        if image_bytes:
            parts.append({"inline_data":{"mime_type":mime_type or "image/jpeg","data":image_bytes}})
        response = client.models.generate_content(model=os.getenv("GEMINI_MODEL","gemini-2.5-flash"), contents=parts)
        text = response.text or ""
        return {"planner":"AI Recommendation","summary":text,"recommendations":[],"note":"Generated by Gemini."}
    except Exception as e:
        return {"error":str(e)}

@app.get("/", response_class=HTMLResponse)
def home(request: Request):
    return templates.TemplateResponse("index.html", {"request":request, "user":get_user(request)})

@app.get("/register", response_class=HTMLResponse)
def register_page(request: Request):
    return templates.TemplateResponse("register.html", {"request":request, "user":get_user(request)})

@app.post("/register")
def register(request: Request, name: str=Form(...), email: str=Form(...), password: str=Form(...)):
    con=db()
    try:
        cur=con.execute("INSERT INTO users(name,email,password) VALUES(?,?,?)",(name,email,password))
        con.commit(); uid=cur.lastrowid
        request.session["user_id"]=uid
        return RedirectResponse("/", status_code=303)
    except sqlite3.IntegrityError:
        return templates.TemplateResponse("register.html", {"request":request,"error":"Email already registered."})
    finally: con.close()

@app.get("/login", response_class=HTMLResponse)
def login_page(request: Request):
    return templates.TemplateResponse("login.html", {"request":request})

@app.post("/login")
def login(request: Request, email: str=Form(...), password: str=Form(...)):
    con=db(); row=con.execute("SELECT * FROM users WHERE email=? AND password=?",(email,password)).fetchone(); con.close()
    if not row:
        return templates.TemplateResponse("login.html", {"request":request,"error":"Invalid email or password."})
    request.session["user_id"]=row["id"]
    return RedirectResponse("/", status_code=303)

@app.get("/logout")
def logout(request: Request):
    request.session.clear()
    return RedirectResponse("/", status_code=303)

@app.get("/planner/home", response_class=HTMLResponse)
def home_planner(request: Request):
    return templates.TemplateResponse("home_planner.html", {"request":request,"user":get_user(request)})

@app.get("/planner/party", response_class=HTMLResponse)
def party_planner(request: Request):
    return templates.TemplateResponse("party_planner.html", {"request":request,"user":get_user(request)})

@app.get("/planner/jewelry", response_class=HTMLResponse)
def jewelry_planner(request: Request):
    return templates.TemplateResponse("jewelry_planner.html", {"request":request,"user":get_user(request)})

@app.post("/generate-home", response_class=HTMLResponse)
async def generate_home(request: Request, budget: float=Form(...), room: str=Form(...), style: str=Form(...)):
    data={"budget":budget,"room":room,"style":style}
    prompt=f"Create budget-aware home interior recommendations. Budget ₹{budget}. Room: {room}. Style: {style}. Return concise item, estimated price, platform and reason."
    result=await gemini_generate(prompt)
    if not result or result.get("error"): result=fallback_home(budget,room,style)
    user=get_user(request)
    if user: save_history(user["id"],"Home",budget,data,result)
    return templates.TemplateResponse("results.html",{"request":request,"result":result,"title":"Home Recommendations","user":user})

@app.post("/generate-party", response_class=HTMLResponse)
async def generate_party(request: Request, budget: float=Form(...), guests: int=Form(...), event: str=Form(...)):
    data={"budget":budget,"guests":guests,"event":event}
    prompt=f"Plan a {event} for {guests} guests with total budget ₹{budget}. Allocate budget for food, venue, decoration and entertainment. Suggest platforms."
    result=await gemini_generate(prompt)
    if not result or result.get("error"): result=fallback_party(budget,guests,event)
    user=get_user(request)
    if user: save_history(user["id"],"Party",budget,data,result)
    return templates.TemplateResponse("results.html",{"request":request,"result":result,"title":"Party Recommendations","user":user})

@app.post("/generate-jewelry", response_class=HTMLResponse)
async def generate_jewelry(request: Request, budget: float=Form(...), occasion: str=Form(...), style: str=Form(...), outfit: UploadFile=File(None)):
    data={"budget":budget,"occasion":occasion,"style":style}
    image_bytes=None
    if outfit and outfit.filename:
        image_bytes=await outfit.read()
        safe=Path(outfit.filename).name
        (UPLOAD_DIR/safe).write_bytes(image_bytes)
        data["image"]=safe
    prompt=f"Recommend jewelry for occasion {occasion}, style {style}, budget ₹{budget}. Consider outfit image if provided."
    result=await gemini_generate(prompt,image_bytes,outfit.content_type if outfit else None)
    if not result or result.get("error"): result=fallback_jewelry(budget,occasion,style)
    user=get_user(request)
    if user: save_history(user["id"],"Jewelry",budget,data,result)
    return templates.TemplateResponse("results.html",{"request":request,"result":result,"title":"Jewelry Recommendations","user":user})

@app.get("/history", response_class=HTMLResponse)
def history(request: Request):
    user=get_user(request)
    if not user: return RedirectResponse("/login", status_code=303)
    con=db(); rows=con.execute("SELECT * FROM history WHERE user_id=? ORDER BY id DESC",(user["id"],)).fetchall(); con.close()
    return templates.TemplateResponse("history.html",{"request":request,"rows":rows,"user":user})

@app.get("/session-info")
def session_info(request: Request):
    user=get_user(request)
    return {"logged_in":bool(user),"user_id":user["id"] if user else None}

@app.get("/health")
def health():
    return {"status":"ok","project":"PocketSmart AI"}

if __name__=="__main__":
    import uvicorn
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)
